services:
  nestjs-boilerplate-api:
    image: nestjs-boilerplate-api
    container_name: nestjs-boilerplate-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - nestjs-boilerplate-network

  db:
    image: postgres:16
    container_name: nestjs-boilerplate-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nestjs_boilerplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "25432:5432"
    networks:
      - nestjs-boilerplate-network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "18080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    env_file:
      - .env
    networks:
      - nestjs-boilerplate-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  nestjs-boilerplate-network:
    driver: bridge
